build-legicash:
  image: registry.gitlab.com/legicash/legicash-facts:build-env
  script:
    # run test net in "dev" mode
    - ./scripts/ethereum-testnet/run.sh
    # build and run Legicash
    - make && make test
    - ./src/_build/default/hello_legicash.exe
