build-legicash:
  image: registry.gitlab.com/legicash/legicash-facts:build-env
  script:
    # Run ethereum test net in "dev" mode
    - make run_ethereum_net
    # Build Legicash
    - make toplevel
    # Run unit tests
    - make test_hello test
