build-legicash:
  image: registry.gitlab.com/legicash/legicash-facts:build-env
  script:
    # Run ethereum test net in "dev" mode
    - make run-ethereum-net
    # Build Legicash
    - make toplevel
    # Run unit tests
    - make test
    - [ "$(echo 'Printf.printf "%s" (Hex.parse_0x_data "0x48656c6c6f2c20776f726c64210a"); exit 0;;' | ./bin/legicaml -no-version -noprompt -noinit)" = "Hello, world!" ]
