before_script:
  # Debian packages
  - apt-get update -y
  - apt-get install -y unzip aspcud opam libsecp256k1-dev
  # Install OPAM, OCaml
  - opam init
  - opam switch 4.06.1
  - eval `opam config env`
    
build-legicash:
  script:
    - ./scripts/install-tezos.sh
    - opam install -y cryptokit secp256k1
    - make
