before_script:
  # Debian packages
  - apt-get update -y
  - apt-get install -y unzip aspcud libgmp-dev dh-autoreconf opam
  # install secp256k1 library from sources
  - ./scripts/install-secp256k1.sh
  # Install OPAM, OCaml
  - opam init
  - opam switch 4.06.1
  - eval `opam config env`

build-legicash:
  script:
    - opam install -y cryptokit jane-street-tests ppx_deriving secp256k1
    - make test
    - make
    - ./src/_build/default/hello_legicash.exe
