build-legicash:
  image: registry.gitlab.com/legicash/legicash-facts:build-env
  script:
    # run test net in "dev" mode
    - make ethereum-net
    # build and run Legicash
    - make && make test
    - ./_build/default/src/hello_legicash.exe
