#!/usr/bin/perl -w

use strict;
use warnings;

my $uu=scalar(@ARGV);

if ($uu ne 1)
{
    print "The script CreateNewConfigFile [LogFile]\n";
    print "It takes the log as input, the input file and returns in standard output the new file\n";
    die;
}

my $eLOGfile = $ARGV[0];


open(INFILE, $eLOGfile) or die "impossible to open LOG file=".$eLOGfile;
my @Blog=<INFILE>;
close(INFILE);

my @ListEnt=("contract_address", "code_hash", "creation_hash", "creation_block");
my $nbEnt=scalar(@ListEnt);


my $nb_found=0;

for (my $iEnt=0; $iEnt<$nbEnt; $iEnt++)
{
    my $eEnt=$ListEnt[$iEnt];
    my $eEntExt="\"".$eEnt."\"";
    #
    my $iLogFound=-1;
    my $OutLine="";
    for (my $iLog=0; $iLog<scalar(@Blog); $iLog++)
    {
        my $eLineLog = $Blog[$iLog];
        my @VG=split($eEntExt, $eLineLog);
        if (scalar(@VG) eq 2)
        {
            $iLogFound = $iLog;
            my @ST=split(",", $VG[1]);
            $OutLine=$ST[0];
        }
    }
    if ($iLogFound eq -1)
    {
        die "Failed to find matching entry for eEnt=".$eEnt."\n";
    }
    if ($iEnt eq 0)
    {
        print "{ ";
    }
    else
    {
        print "  ";
    }
    print $eEntExt.$OutLine;
    if ($iEnt < $nbEnt-1)
    {
        print ",";
    }
    print "\n";
}
print "}\n";
